### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by Tsueipi45** [SteveKunG/SkyBlockcatia#81] opened 2021-05-14 08:47 UTC
while using this mod, my minecraft keep crashing, it says

> The game crashed whilst initializing game
> Error: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/layers/LayerCustomHead

here's the crash log

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  Perspective Mod ([1.8.9] Perspective Mod.jar)
  PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  HCTweaker (HUDCaching-1.7-REL.jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.0-beta.11-for-MC-1.8.9.jar)
  InputFix ([1.8.9] InputFix.jar)
  ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  CTJSLoadingPlugin (ctjs-1.3.1-1.8.9.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 2021/5/14 下午 4:46
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/layers/LayerCustomHead
	at net.minecraft.client.renderer.entity.RenderBiped.<init>(SourceFile:28)
	at net.minecraft.client.renderer.entity.RenderBiped.<init>(SourceFile:18)
	at net.minecraft.client.renderer.entity.RenderSkeleton.<init>(SourceFile:15)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:163)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.layers.LayerCustomHead
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$renderEnchantedSkull$zef000(Lnet/minecraft/client/renderer/tileentity/TileEntitySkullRenderer;FFFLnet/minecraft/util/EnumFacing;FILcom/mojang/authlib/GameProfile;ILnet/minecraft/entity/EntityLivingBase;FFFFFFF)V in mixins.skyblockcatia.json:renderer.entity.layers.LayerCustomHeadMixin failed injection check, (0/1) succeeded. Using refmap mixins.skyblockcatia.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:938)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:322)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderBiped.<init>(SourceFile:28)
	at net.minecraft.client.renderer.entity.RenderBiped.<init>(SourceFile:18)
	at net.minecraft.client.renderer.entity.RenderSkeleton.<init>(SourceFile:15)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:163)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	ct.js modules: [Module{name=AlonAddons,folder=.\config\ChatTriggers\modules\AlonAddons,metadata=ModuleMetadata(name=AlonAddons, version=0.0.82, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=cool changes and barn fishing timer, requires=[Vigilance, requestV2], helpMessage=null, ignored=null, isRequired=false)}, Module{name=CustomTabCompletions,folder=.\config\ChatTriggers\modules\CustomTabCompletions,metadata=ModuleMetadata(name=CustomTabCompletions, version=1.0.2, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=SirHyperNova, description=A module that allows you to add a custom tab completion function to commands., requires=null, helpMessage=null, ignored=null, isRequired=true)}, Module{name=PromiseV2,folder=.\config\ChatTriggers\modules\PromiseV2,metadata=ModuleMetadata(name=PromiseV2, version=1.0.4, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=McPqndq, description=Promise polyfill, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=requestV2,folder=.\config\ChatTriggers\modules\requestV2,metadata=ModuleMetadata(name=requestV2, version=2.0.0, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson (uploaded by McPqndq), description=A nicer alternative to XMLHttpRequest with a promise-like API. See the README.md for a full api description. (PS from McPqndq: this module is a copy paste of Ecolsson's 'request' except using a different Promise polyfill.), requires=[PromiseV2], helpMessage=null, ignored=null, isRequired=false)}, Module{name=SettingsManager,folder=.\config\ChatTriggers\modules\SettingsManager,metadata=ModuleMetadata(name=SettingsManager, version=1.2.2, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Autogenerates a settings file and gui based on the object created and registers. Example usage can be found in UseExample.js, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=soopyAddonsData,folder=.\config\ChatTriggers\modules\soopyAddonsData,metadata=ModuleMetadata(name=soopyAddonsData, version=0.0.1, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Custom soopy stuff., requires=[], helpMessage=null, ignored=null, isRequired=false)}, Module{name=soopyApis,folder=.\config\ChatTriggers\modules\soopyApis,metadata=ModuleMetadata(name=soopyApis, version=0.1.2, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Soopyboo32, description=Some random apis that soopy's mods use, requires=[], helpMessage=null, ignored=null, isRequired=false)}, Module{name=Vigilance,folder=.\config\ChatTriggers\modules\Vigilance,metadata=ModuleMetadata(name=Vigilance, version=1.0.1, entry=test.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=FalseHonesty, description=A CT wrapper for the Vigilance [https://github.com/Sk1erLLC/Vigilance] configuration library., requires=null, helpMessage=null, ignored=null, isRequired=false)}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 425626752 bytes (405 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M6_pre1 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCH	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCH	InputFix{1.8.x-v2} [InputFix] (minecraft.jar) 
	UCH	perspectivemod{3.0} [Perspective Mod 3.0] (minecraft.jar) 
	UCH	autotip{3.0.1} [Autotip] ([1.8.9] Autotip.jar) 
	UCH	modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
	UCH	customcrosshairmod{0.5.1-Forge} [Custom Crosshair Mod] ([1.8.9] Crosshairmod-v0.5.1.jar) 
	UCH	orangesimplemod{1.1} [orangesimplemod] ([1.8.9] Orange's Simple Mods.jar) 
	UCH	sidebarmod{2.0} [Sidebar Mod Revamp] ([1.8.9] SidebarMod.jar) 
	UCH	ct.js{1.3.1} [ChatTriggers] (ctjs-1.3.1-1.8.9.jar) 
	UCH	hudcaching{1.7-REL} [HUDCaching] (HUDCaching-1.7-REL.jar) 
	UCH	notenoughupdates{2.0.0-REL} [NotEnoughUpdates] (NotEnoughUpdates-2.0-PRE27.jar) 
	UCH	patcher{1.5.1} [Patcher] (Patcher-1.5.1 (1.8.9).jar) 
	UCH	sbitemrename{1.0} [SBItemRename] (SBItemRename.jar) 
	UCH	text_overflow_scroll{1.3} [Scrollable Tooltips] (Scrollable Tooltips-1.3 (1.8.9).jar) 
	UCH	skyblockaddons{1.6.0-beta.11} [SkyblockAddons] (SkyblockAddons-1.6.0-beta.11-for-MC-1.8.9.jar) 
	UCH	skyblockcatia{1.1.2} [SkyBlockcatia] (SkyBlockcatia-1.8.9-1.1.2.jar) 
	UCH	SkyblockExtras{2.0.6} [SkyblockExtras] (SkyblockExtras-2.0.6.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
Perspective Mod ([1.8.9] Perspective Mod.jar)
  net.canelex.perspectivemod.asm.CameraTransformer
PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.patcher.tweaker.ClassTransformer
HCTweaker (HUDCaching-1.7-REL.jar)
  io.github.moulberry.hudcaching.asm.ClassTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.0-beta.11-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
InputFix ([1.8.9] InputFix.jar)
  lain.mods.inputfix.InputFixTransformer
ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
CTJSLoadingPlugin (ctjs-1.3.1-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 465.89' Renderer: 'NVIDIA GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 465.89, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !     §4Inferno, §r§lFurfSky §6§lReborn §8§lOV §8§l[§71.2.6§8§l].zip, Skyblock Mob Pack
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M6_pre1
	OptiFine Build: 20210326-211438
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 465.89
	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by SteveKunG** [comment] 2021-05-14 08:48
Duplicate of #80

**Closed as completed by SteveKunG** 2021-05-14 08:48 UTC
